### PR TITLE
adding go.mod

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I'm new to Go, and I was checking this example... and the way I fixed was by adding the go.mod. decided to send a PR with the fix.

let me know what you need to complete the PR.

**Comment by clebertsuconic** [comment]
I'm new to Go, and I was checking this example... and the way I fixed was by adding the go.mod. decided to send a PR with the fix.

let me know what you need to complete the PR.

**Comment by miekg** [comment]
Go.mod can create a cyclic dependency when compiling with coredns , so it's
better to forgo them in these cases

**Comment by clebertsuconic** [comment]
@miekg well, you need to document how to build this then.

I built core-dns.. then downloaded the example... it does not build with this.


There's no cyclic dependency here.. the example depends on the plugin. and that's it.

**Comment by clebertsuconic** [comment]
I just realized you removed modules not long ago.

The project does not build currently. perhaps it builds in your local laptop... but on a new environment it does not build.


in case I need some steps to follow.. that's fine, but that would need to be documented.

**Comment by clebertsuconic** [comment]
Please, consider keeping a module setting. you probably had some version mismatch on your previous version. If you decide on keeping it off, please document on how to build this... otherwise keep it simple, and keep the module! ;) 


thanks

/me done.. let me know what you want to do.. I can build this myself.. I just wished somebody else wouldn't encounter the same simple issue.

**Comment by johnbelamaric** [comment]
You may want to look at coredns/learning-coredns/plugins/onlyone which is
another example that does use go.mod

**Comment by clebertsuconic** [comment]
@johnbelamaric that's another reason to merge my PR :)

thanks though

**Comment by clebertsuconic** [comment]
@johnbelamaric thanks a lot.

@miekg another reason to place mod back in... please!!!

**Comment by clebertsuconic** [comment]
Of course you can’t.  The issue is for new installations where you don’t have the objects in the path. 


If you don’t care.  It’s up to you.  At least it’s documented and it does not compile on a brand new installation.

**Comment by clebertsuconic** [comment]
I must apologize.. I see now that the code needs to be compiled within coredns, not in a standalone form.

anyway... perhaps we could update the README on the example on how to use it.


thanks a lot.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/example] adding go.mod..." ]
>I must apologize.. I see now that the code needs to be compiled within coredns, not in a standalone form.
>
>anyway... perhaps we could update the README on the example on how to use it.

thank you. I think that makes sense. Do you want to propose some text? Probaly needs to
include a link to coredns.io as well, in a See Also section.

**Comment by clebertsuconic** [comment]
@miekg added #10 based on this discussion. Let me know if you want me to amend anything on that PR. 


thanks a lot.

**Pull request closed without merging**
